version: '3'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
     - "5001:5000"
    networks:
      - default
    depends_on:
      - sqldb
      - rabbitmq
    logging:
      options:
        max-size: "3m"
        max-file: "3"
  sqldb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'H77i890'
      MYSQL_DATABASE: magnit_db
      MYSQL_USER: magnit_db
      MYSQL_PASSWORD: 'test_dev'
    volumes:
      - ./conf/db/db.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "3307:3306"
    networks:
      - default
    logging:
      options:
        max-size: "3m"
        max-file: "3"
  rabbitmq:
    restart: "no"
    image: rabbitmq:3.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmagnit
      - RABBITMQ_DEFAULT_PASS=rabbit_test
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      - default
    logging:
      options:
        max-size: "3m"
        max-file: "3"
  celery:
    build: .
#    command: sh -c "celery -A app.tasks beat -l info && celery -A app.tasks worker -l info --pool=prefork"
    command: celery -A app.tasks worker -l info -B
    volumes:
      - .:/code
    depends_on:
      - web
networks:
  default:
    driver: bridge
