###
POST http://localhost:5000/
Content-Type: application/json

{}

###

POST http://localhost:5001/registration
Content-Type: application/json

{"name": "TestUser2", "email": "s.pertak@gmail.com", "password": "12345"}

###

POST http://localhost:5000/login
Content-Type: application/json

{"email": "test4@gmail.com", "password": "12345"}

###

POST http://localhost:5001/auctions/auction
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyMzA0NDIwMiwianRpIjoiODFmYjk4NGYtMjdmYi00YmIwLWFjMzEtYjZlODU1NTM3OGI4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjIzMDQ0MjAyLCJleHAiOjE2MjUxMTc4MDJ9.mKWJdErZvMA6POT0-XGmzunA9wxh88lWDA4UF61RcE4


{
  "description": "Test auction NN",
  "end_auction": "2021-06-10T14:45:49.693Z",
  "first_cost": 1,
  "is_active": true,
  "name": "WWW",
  "start_auction": "2021-06-05T14:42:49.693Z",
  "step_cost": -10
}

###

GET http://localhost:5000/auctions
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyMjgxMTA0NCwianRpIjoiMmU2NjU4YTktOTJlMC00NmEyLWE5ZDQtMmI2NWNmZDQ2MDhkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjIyODExMDQ0LCJleHAiOjE2MjQ4ODQ2NDR9.5nNiENgOYc289-SIeZ2jJtKXBUfQj8wRYrfRHGSj_HI

###

POST http://localhost:5001/auctions
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyMjgxMTA0NCwianRpIjoiMmU2NjU4YTktOTJlMC00NmEyLWE5ZDQtMmI2NWNmZDQ2MDhkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjIyODExMDQ0LCJleHAiOjE2MjQ4ODQ2NDR9.5nNiENgOYc289-SIeZ2jJtKXBUfQj8wRYrfRHGSj_HI

{"is_active": true}

###

GET http://localhost:5000/auctions/auction/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyMjgxMTA0NCwianRpIjoiMmU2NjU4YTktOTJlMC00NmEyLWE5ZDQtMmI2NWNmZDQ2MDhkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6NCwibmJmIjoxNjIyODExMDQ0LCJleHAiOjE2MjQ4ODQ2NDR9.5nNiENgOYc289-SIeZ2jJtKXBUfQj8wRYrfRHGSj_HI

###

POST http://localhost:5000/bet
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyMjkyNTY2MiwianRpIjoiY2I5OWQyMjEtN2RjOC00YjRmLThkMWQtZGZiOTgyMDc3NWFmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MzYsIm5iZiI6MTYyMjkyNTY2MiwiZXhwIjoxNjI0OTk5MjYyfQ.KBvFosKlw0K2uMa-Y6dqpofVLw6H9VA340jA3M10EMg

{
  "auction_id": 1,
  "cost": 1211
}

###